site_name: OSI Layer 8
site_description: Our CTF writeups
site_author: OSI Layer 8
site_url: https://osilayer8.cf/

repo_name: nushosilayer8
repo_url: https://github.com/nushosilayer8/writeups/
edit_uri: edit/master/writeups/

docs_dir: writeups

theme: 
  name: material
  logo: img/logo_white.svg
  palette: 
    primary: light blue
    accent: blue

pages:
  - Home: README.md

  - CrossCTF 2018 Qualifiers: 
    - Overview: crossctf-quals2018/README.md
    - CYOA: crossctf-quals2018/CYOA/README.md
    - Even Flow: crossctf-quals2018/pwn/evenflow/README.md
    - BabyRSA: crossctf-quals2018/crypto/BabyRSA/README.md
    - BabyRSA 2: crossctf-quals2018/crypto/BabyRSA2/README.md

  - CrossCTF 2018 Finals:
    - Overview: crossctf-finals2018/README.md
    - Pwn:
      - FTLOG: crossctf-finals2018/pwn/ftlog/README.md
      - Slowmo: crossctf-finals2018/pwn/slowmo/README.md
      - Coca Cola: crossctf-finals2018/pwn/cocacola/README.md
      - GruffyBear: crossctf-finals2018/pwn/gruffybear/README.md
      - Souvlaki Space Station: crossctf-finals2018/pwn/souvlaki/README.md
    - Reversing:
      - Perfect: crossctf-finals2018/re/perfect/README.md
      - 'Tower Of Beer: Rochefort 6': crossctf-finals2018/re/rochefort6/README.md
      - 'Tower Of Beer: Rochefort 8': crossctf-finals2018/re/rochefort8/README.md
      - iamrusty: crossctf-finals2018/re/iamrusty/README.md
    - Web:
      - GoCoin!: crossctf-finals2018/web/gocoin/README.md
      - GoCoin! Plus: crossctf-finals2018/web/gocoinplus/README.md
      - GoCoin! Plus Plus: crossctf-finals2018/web/gocoinplusplus/README.md
      - The Terminal: crossctf-finals2018/web/terminal/README.md
      - RetroWeb: crossctf-finals2018/web/retroweb/README.md
      - CacheCreek: crossctf-finals2018/web/cachecreek/README.md
    - Crypto:
      - Fitblips: crossctf-finals2018/crypto/fitblips/README.md
      - BabyRSA: crossctf-finals2018/crypto/babyrsa3/README.md
    - Misc:
      - The Evilness: crossctf-finals2018/misc/evil/README.md
      - Choose Your Own Adventure: crossctf-finals2018/misc/cyoa/cyoa.py
    - Mobile:
      - Human Powered Flag Generator: crossctf-finals2018/mobile/human/README.md

  - GoogleCTF 2018 Qualifiers:
    - Overview: googlectf-quals2018/README.md
    - Reversing:
      - Shall we play a game: googlectf-quals2018/re/shallweplayagame/README.md
# vim: noai:ts=2:sw=2
