site_name: OSI Layer 8
site_url: https://nush-osi-layer-8.github.io/writeups/
repo_url: https://github.com/nush-osi-layer-8/writeups/
docs_dir: 'writeups'

theme: 
    name: 'material'
    palette: 
        primary: 'light blue'
        accent: 'blue'
